### ISSUE TITLE
iptables problem

### ISSUE THREAD

**Issue by puupuu** [FunctionClub/SSR-Bash#1]
when service is started, the below message continues showing:
"""
iptables v1.4.21: can't initialize iptables table `filter': Permission denied (you must be root)
Perhaps iptables or your kernel needs to be upgraded.
iptables v1.4.21: can't initialize iptables table `filter': Permission denied (you must be root)
Perhaps iptables or your kernel needs to be upgraded.
"""
user is root
Linux 233e17484cfc 4.8.6-coreos #1 SMP Thu Nov 3 04:43:35 UTC 2016 x86_64 GNU/Linux

add more information:
"""
~# iptables --version
iptables v1.4.21
~# service iptables status
iptables: unrecognized service
"""

**Comment by KiritoMiao** [comment]
请执行"service iptables status"并提交反馈结果

**Comment by qinchan** [comment]
help to translate the solution：

Please run the script: `service iptables status`  and thengive us a respond

**Comment by puupuu** [comment]
the information updated in the issue description as requested to run "service iptables status"

**Comment by KiritoMiao** [comment]
It seems that the iptables on your server have some problem, I will add a sample report about "service iptables status"

**Comment by KiritoMiao** [comment]
[root@iZwz90ax1n8w9qrs9zr7e0Z ~]# service iptables status
Table: filter
Chain INPUT (policy DROP)
num  target     prot opt source               destination
1    f2b-SSH    tcp  --  0.0.0.0/0            0.0.0.0/0           tcp dpt:22
2    ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0
3    ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0           state RELATED,ESTABLISHED
4    ACCEPT     tcp  --  0.0.0.0/0            0.0.0.0/0           state NEW tcp dpt:22
5    ACCEPT     tcp  --  0.0.0.0/0            0.0.0.0/0           state NEW tcp dpt:80
6    ACCEPT     tcp  --  0.0.0.0/0            0.0.0.0/0           state NEW tcp dpt:443
7    ACCEPT     icmp --  0.0.0.0/0            0.0.0.0/0           limit: avg 1/sec burst 10
8    ACCEPT     all  -f  0.0.0.0/0            0.0.0.0/0           limit: avg 100/sec burst 100
9    syn-flood  tcp  --  0.0.0.0/0            0.0.0.0/0           tcp flags:0x17/0x02
10   REJECT     all  --  0.0.0.0/0            0.0.0.0/0           reject-with icmp-host-prohibited

Chain FORWARD (policy ACCEPT)
num  target     prot opt source               destination

Chain OUTPUT (policy ACCEPT)
num  target     prot opt source               destination

Chain f2b-SSH (1 references)
num  target     prot opt source               destination
1    REJECT     all  --  121.42.0.30          0.0.0.0/0           reject-with icmp-port-unreachable
2    REJECT     all  --  113.119.193.79       0.0.0.0/0           reject-with icmp-port-unreachable
3    REJECT     all  --  120.77.52.253        0.0.0.0/0           reject-with icmp-port-unreachable
4    REJECT     all  --  121.41.121.184       0.0.0.0/0           reject-with icmp-port-unreachable
5    REJECT     all  --  139.196.76.189       0.0.0.0/0           reject-with icmp-port-unreachable
6    REJECT     all  --  120.77.59.26         0.0.0.0/0           reject-with icmp-port-unreachable
7    RETURN     all  --  0.0.0.0/0            0.0.0.0/0

Chain syn-flood (1 references)
num  target     prot opt source               destination
1    RETURN     tcp  --  0.0.0.0/0            0.0.0.0/0           limit: avg 3/sec burst 6
2    REJECT     all  --  0.0.0.0/0            0.0.0.0/0           reject-with icmp-port-unreachable

[root@iZwz90ax1n8w9qrs9zr7e0Z ~]#

**Comment by KiritoMiao** [comment]
You can try to restall iptables to fix the problem

**Comment by qinchan** [comment]
reinstall
