### ISSUE TITLE
关于ipv6

### ISSUE THREAD

**Issue by hwplay123** [FunctionClub/SSR-Bash#2]
节点服务器IP就是我的VPS IP吧？
这个对应的有ipv6的节点吗，如果VPS有IPV6地址的话？
是不是直接就创建好了ipv6？（我不需要监控ipv6的流量，但我需要ipv6）

**Comment by KiritoMiao** [comment]
默认应该是监听0.0.0.0，具体情况已经通知wmy来回答

**Comment by KiritoMiao** [comment]
问题已解决，关闭issue
