### ISSUE TITLE
SSR启动失败

### ISSUE THREAD

**Issue by ly12lil** [FunctionClub/SSR-Bash#7]
5464 pts/0    S      0:00 /bin/bash /usr/local/SSR-Bash/sscounter.sh
sscounter启动中...
 5544 pts/0    S+     0:00 /bin/bash /usr/local/SSR-Bash/sscounter.sh
sscounter已启动
SSR启动中...
loaded collections.OrderedDict
IPv6 support
2017-02-15 13:37:55 ERROR    shell.py:99 password or port_password not specified
usage: ssserver [OPTION]...
A fast tunnel proxy that helps you bypass firewalls.

You can supply configurations via either config file or command line arguments.

Proxy options:
  -c CONFIG              path to config file
  -s SERVER_ADDR         server address, default: 0.0.0.0
  -p SERVER_PORT         server port, default: 8388
  -k PASSWORD            password
  -m METHOD              encryption method, default: aes-256-cfb
  -o OBFS                obfsplugin, default: http_simple
  -t TIMEOUT             timeout in seconds, default: 300
  --fast-open            use TCP_FASTOPEN, requires Linux 3.7+
  --workers WORKERS      number of workers, available on Unix/Linux
  --forbidden-ip IPLIST  comma seperated IP list forbidden to connect
  --manager-address ADDR optional server manager UDP address, see wiki

General options:
  -h, --help             show this help message and exit
  -d start/stop/restart  daemon mode
  --pid-file PID_FILE    pid file for daemon mode
  --log-file LOG_FILE    log file for daemon mode
  --user USER            username to run as
  -v, -vv                verbose mode
  -q, -qq                quiet mode, only show warnings/errors
  --version              show version information

Online help: <https://github.com/shadowsocks/shadowsocks>

SSR启动失败

**Comment by YLWS-4617** [comment]
嗯嗯，已经在脚本里把ssr版本换成老版本了，问题解决了，重装下系统，跑一遍脚本就好了～
